{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "544dd802",
   "metadata": {},
   "source": [
    "# Dimensionality Reduction\n",
    "#### Roles and Buckets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4714b1de",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install mxnet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "18aa39c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# sagemaker libraries\n",
    "import boto3\n",
    "import sagemaker\n",
    "from sagemaker import get_execution_role\n",
    "\n",
    "# pandas and np\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a23788a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "af92cb99",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "arn:aws:iam::305472246504:role/service-role/AmazonSageMaker-ExecutionRole-20210617T231874\n"
     ]
    }
   ],
   "source": [
    "session = sagemaker.Session() # store the current SageMaker session\n",
    "\n",
    "# get IAM role\n",
    "role = get_execution_role()\n",
    "print(role)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e6987b8c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker-us-east-1-305472246504\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# get default bucket\n",
    "bucket = session.default_bucket()\n",
    "print(bucket)\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1ac6d223",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "s3://sagemaker-us-east-1-305472246504/starbucks/pca-2021-06-18-05-52-03-430/output\n"
     ]
    }
   ],
   "source": [
    "# should be the name of directory you created to save your features data\n",
    "data_dir = 'saved_progress'\n",
    "\n",
    "# set prefix, a descriptive name for a directory  \n",
    "prefix = 'starbucks/pca-2021-06-18-05-52-03-430/output'\n",
    "\n",
    "# upload all data to S3\n",
    "input_data = session.upload_data(path=data_dir, bucket=bucket, key_prefix=prefix)\n",
    "print(input_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0a5668b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "0873fea6",
   "metadata": {},
   "source": [
    "#### Define a PCA Model\n",
    "* role: The IAM role, which was specified, above.\n",
    "* train_instance_count: The number of training instances (typically, 1).\n",
    "* train_instance_type: The type of SageMaker instance for training.\n",
    "* num_components: An integer that defines the number of PCA components to produce.\n",
    "* sagemaker_session: The session used to train on SageMaker."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2126fe9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define location to store model artifacts\n",
    "prefix = 'starbucks'\n",
    "\n",
    "output_path='s3://{}/{}/'.format(bucket_name, prefix)\n",
    "\n",
    "print('Training artifacts will be uploaded to: {}'.format(output_path))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c33db73",
   "metadata": {},
   "outputs": [],
   "source": [
    "data_scaled.shape[1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7b361c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define a PCA model\n",
    "from sagemaker import PCA\n",
    "\n",
    "data_scaled = pd.read_csv('saved_progress/scaled_dataset.csv')\n",
    "data_scaled.drop(columns=['Unnamed: 0'], inplace=True)\n",
    "\n",
    "# this is current features - 1\n",
    "# you'll select only a portion of these to use, later\n",
    "N_COMPONENTS = data_scaled.shape[1] - 1\n",
    "\n",
    "pca_starbucks = PCA(role=role,\n",
    "             instance_count=1,\n",
    "             instance_type='ml.p2.xlarge',\n",
    "             output_path=output_path, # specified, above\n",
    "             num_components=N_COMPONENTS, \n",
    "             sagemaker_session=session)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f3d7500e",
   "metadata": {},
   "source": [
    "#### Convert data into a RecordSet format¶\n",
    "Next, prepare the data for a built-in model by converting the DataFrame to a numpy array of float values.\n",
    "\n",
    "The record_set function in the SageMaker PCA model converts a numpy array into a RecordSet format that is the required format for the training input data. This is a requirement for all of SageMaker's built-in models. The use of this data type is one of the reasons that allows training of models within Amazon SageMaker to perform faster, especially for large datasets."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25bcc1ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "# convert df to np array\n",
    "train_data_np = data_scaled.values.astype('float32')\n",
    "\n",
    "# convert to RecordSet format\n",
    "formatted_train_data = pca_starbucks.record_set(train_data_np)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "567cd5de",
   "metadata": {},
   "source": [
    "#### Train the model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "05a00526",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "\n",
    "# train the PCA mode on the formatted data\n",
    "pca_starbucks.fit(formatted_train_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3fc66543",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get the name of the training job, it's suggested that you copy-paste\n",
    "# from the notebook or from a specific job in the AWS console\n",
    "training_job_name='pca-2021-06-18-05-52-03-430'\n",
    "\n",
    "# where the model is saved, by default\n",
    "model_key = os.path.join(prefix, training_job_name, 'output/model.tar.gz')\n",
    "print(model_key)\n",
    "\n",
    "# download and unzip model\n",
    "boto3.resource('s3').Bucket(bucket_name).download_file(model_key, 'model.tar.gz')\n",
    "\n",
    "# unzipping as model_algo-1\n",
    "os.system('tar -zxvf model.tar.gz')\n",
    "os.system('unzip model_algo-1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c42f8c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mxnet as mx\n",
    "\n",
    "# loading the unzipped artifacts\n",
    "pca_model_params = mx.ndarray.load('model_algo-1')\n",
    "\n",
    "# what are the params\n",
    "print(pca_model_params)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e923286c",
   "metadata": {},
   "source": [
    "#### PCA Model Attributes\n",
    "Three types of model attributes are contained within the PCA model.\n",
    "\n",
    "**mean**: The mean that was subtracted from a component in order to center it.\n",
    "\n",
    "**v**: The makeup of the principal components; (same as ‘components_’ in an sklearn PCA model).\n",
    "\n",
    "**s**: The singular values of the components for the PCA transformation. This does not exactly give the % variance from the original feature space, but can give the % variance from the projected feature space.\n",
    "\n",
    "We are only interested in v and s."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f08c180",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get selected params\n",
    "s=pd.DataFrame(pca_model_params['s'].asnumpy())\n",
    "v=pd.DataFrame(pca_model_params['v'].asnumpy())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2a387bfd",
   "metadata": {},
   "source": [
    "#### Data Variance\n",
    "Our current PCA model creates 33 principal components, but when we create new dimensionality-reduced training data, we'll only select a few, top n components to use. To decide how many top components to include, it's helpful to look at how much data variance the components capture.\n",
    "\n",
    "\n",
    "\n",
    "When we select the top n components to use in a new data model, we'll typically want to include enough components to capture about 80-90% of the original data variance. In this project, we are looking at generalizing over a lot of data and we'll aim for about 85% coverage.\n",
    "\n",
    "Note: The top principal components, with the largest s values, are actually at the end of the s DataFrame. Let's print out the s values for the top n, principal components."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90cb131d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# looking at top 5 components\n",
    "n_principal_components = 5\n",
    "\n",
    "start_idx = N_COMPONENTS - n_principal_components  \n",
    "\n",
    "# print a selection of s\n",
    "print(s.iloc[start_idx:, :])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "272f4ec0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def explained_variance(s, n_top_components):\n",
    "    '''Calculates the approx. data variance that n_top_components captures.\n",
    "       :param s: A dataframe of singular values for top components; \n",
    "           the top value is in the last row.\n",
    "       :param n_top_components: An integer, the number of top components to use.\n",
    "       :return: The expected data variance covered by the n_top_components.'''\n",
    "    \n",
    "    start_idx = N_COMPONENTS - n_top_components \n",
    "    # calculate approx variance\n",
    "    exp_variance = np.square(s.iloc[start_idx:,:]).sum()/np.square(s).sum()\n",
    "    \n",
    "    return exp_variance[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69f45c71",
   "metadata": {},
   "outputs": [],
   "source": [
    "# test cell\n",
    "n_top_components = 5 # select a value for the number of top components\n",
    "\n",
    "# calculate the explained variance\n",
    "exp_variance = explained_variance(s, n_top_components)\n",
    "print('Explained variance: ', exp_variance)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d2936228",
   "metadata": {},
   "source": [
    "#### Component Makeup\n",
    "We can now examine the makeup of each PCA component based on **the weightings of the original features that are included in the component**. The following code shows the feature-level makeup of the first component.\n",
    "\n",
    "Note that the components are again ordered from smallest to largest and so I am getting the correct rows by calling N_COMPONENTS-1 to get the top, 1, component."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8f202c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns \n",
    "\n",
    "def display_component(v, features_list, component_num, n_weights=10):\n",
    "    \n",
    "    # get index of component (last row - component_num)\n",
    "    row_idx = N_COMPONENTS-component_num\n",
    "\n",
    "    # get the list of weights from a row in v, dataframe\n",
    "    v_1_row = v.iloc[:, row_idx]\n",
    "    v_1 = np.squeeze(v_1_row.values)\n",
    "\n",
    "    # match weights to features in counties_scaled dataframe, using list comporehension\n",
    "    comps = pd.DataFrame(list(zip(v_1, features_list)), \n",
    "                         columns=['weights', 'features'])\n",
    "\n",
    "    # we'll want to sort by the largest n_weights\n",
    "    # weights can be neg/pos and we'll sort by magnitude\n",
    "    comps['abs_weights']=comps['weights'].apply(lambda x: np.abs(x))\n",
    "    sorted_weight_data = comps.sort_values('abs_weights', ascending=False).head(n_weights)\n",
    "\n",
    "    # display using seaborn\n",
    "    ax=plt.subplots(figsize=(10,6))\n",
    "    ax=sns.barplot(data=sorted_weight_data, \n",
    "                   x=\"weights\", \n",
    "                   y=\"features\", \n",
    "                   palette=\"Blues_d\")\n",
    "    ax.set_title(\"PCA Component Makeup, Component #\" + str(component_num))\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b74180e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# display makeup of first component\n",
    "num = 5\n",
    "display_component(v, data_scaled.columns.values, component_num=num, n_weights=10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "30d4f2a5",
   "metadata": {},
   "source": [
    "#### Deploying the PCA Model\n",
    "We can now deploy this model and use it to make \"predictions\". Instead of seeing what happens with some test data, we'll actually want to pass our training data into the deployed endpoint to create principal components for each data point."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e8651a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "# this takes a little while, around 8mins\n",
    "pca_predictor = pca_starbucks.deploy(initial_instance_count=1, \n",
    "                              instance_type='ml.p2.xlarge')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0fb062ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "# pass np train data to the PCA model\n",
    "train_pca = pca_predictor.predict(train_data_np)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ce8b1ec",
   "metadata": {},
   "outputs": [],
   "source": [
    "# check out the first item in the produced training features\n",
    "data_idx = 0\n",
    "print(train_pca[data_idx])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17262529",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def create_transformed_df(train_pca, data_scaled, n_top_components):\n",
    "    ''' Return a dataframe of data points with component features. \n",
    "        The dataframe should be indexed by State-County and contain component values.\n",
    "        :param train_pca: A list of pca training data, returned by a PCA model.\n",
    "        :param counties_scaled: A dataframe of normalized, original features.\n",
    "        :param n_top_components: An integer, the number of top components to use.\n",
    "        :return: A dataframe, indexed by State-County, with n_top_component values as columns.        \n",
    "     '''\n",
    "    # create new dataframe to add data to\n",
    "    data_transformed=pd.DataFrame()\n",
    "\n",
    "    # for each of our new, transformed data points\n",
    "    # append the component values to the dataframe\n",
    "    for data in train_pca:\n",
    "        # get component values for each data point\n",
    "        components=data.label['projection'].float32_tensor.values\n",
    "        data_transformed = data_transformed.append([list(components)])\n",
    "\n",
    "    # index by county, just like counties_scaled\n",
    "    data_transformed.index = data_scaled.index\n",
    "\n",
    "    # keep only the top n components\n",
    "    start_idx = N_COMPONENTS - n_top_components\n",
    "    data_transformed = data_transformed.iloc[:,start_idx:]\n",
    "    \n",
    "    # reverse columns, component order     \n",
    "    return data_transformed.iloc[:, ::-1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9b54e89",
   "metadata": {},
   "outputs": [],
   "source": [
    "# specify top n\n",
    "top_n = 5\n",
    "\n",
    "# call your function and create a new dataframe\n",
    "data_transformed = create_transformed_df(train_pca, data_scaled, n_top_components=top_n)\n",
    "\n",
    "# add descriptive columns\n",
    "PCA_list=['c_1', 'c_2', 'c_3', 'c_4', 'c_5']\n",
    "data_transformed.columns=PCA_list \n",
    "\n",
    "# print result\n",
    "data_transformed.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4384b38d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Save PCA dataset\n",
    "data_transformed.to_csv('saved_progress/pca_scores.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1734379e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Delete predictor endpoint\n",
    "session.delete_endpoint(pca_predictor.endpoint)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2e7f854a",
   "metadata": {},
   "source": [
    "#### Metrics\n",
    "**Eblow method**\n",
    "Inertia measures how well a data set is clustered by K-Means. It is calculated by measuring the distance between each data point and its centroid, squaring this distance and summing these squares into a cluster.\n",
    "\n",
    "A good model is one with low inertia AND a low number of clusters (K). However, this is a trade-off because as K increases, the inertia decreases.\n",
    "\n",
    "To find the optimal K for a data set, use the Elbow method; find the point where the decrease in inertia begins to decrease."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1af2ea8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.cluster import KMeans\n",
    "import sklearn.metrics as metrics\n",
    "\n",
    "scores = []\n",
    "\n",
    "for k in range(1,11):\n",
    "    km = KMeans(n_clusters = k,random_state=1)\n",
    "    km = km.fit(data_transformed)\n",
    "    scores.append(km.inertia_)\n",
    "\n",
    "dfk = pd.DataFrame({'Cluster':range(1,11), 'Score':scores})\n",
    "plt.figure(figsize=(8,5))\n",
    "plt.plot(dfk['Cluster'], dfk['Score'], marker='o')\n",
    "plt.xlabel('Number of clusters')\n",
    "plt.ylabel('Inertia')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41fb292b",
   "metadata": {},
   "source": [
    "#### Silhouette value\n",
    "The silhouette value measures how similar a point is to its own cluster (cohesion) compared to other clusters (separation)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "928c160d",
   "metadata": {},
   "outputs": [],
   "source": [
    "for i in range(2,17):\n",
    "    kmeans_labels=KMeans(n_clusters=i,random_state=1).fit_predict(data_transformed)\n",
    "    print(\"Silhouette score for {} clusters k-means : {} \".format(i,metrics.silhouette_score(data_scaled,kmeans_labels, metric='euclidean').round(3)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c30a9d6f",
   "metadata": {},
   "source": [
    "#### Davies Bouldin\n",
    "Average similarity measure of each cluster to its most similar cluster, where similarity is the ratio of distances within the cluster to distances between clusters. The minimum score is zero, and lower values indicate better clustering."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7439b7e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "for i in range(2, 17):\n",
    "    kmeans_labels=KMeans(n_clusters=i,random_state=1).fit_predict(data_transformed)\n",
    "    print(f'Davies Bouldin Score {i}: {metrics.davies_bouldin_score(data_scaled,kmeans_labels).round(3)}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37d2c696",
   "metadata": {},
   "outputs": [],
   "source": [
    "# define a KMeans estimator\n",
    "from sagemaker import KMeans\n",
    "\n",
    "NUM_CLUSTERS = 3\n",
    "\n",
    "kmeans = KMeans(role=role,\n",
    "                instance_count=1,\n",
    "                instance_type='ml.p2.xlarge',\n",
    "                output_path=output_path, # using the same output path as was defined, earlier              \n",
    "                k=NUM_CLUSTERS)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "27a467d5",
   "metadata": {},
   "source": [
    "#### Create formatted, k-means training data\n",
    "Just as before, you should convert the data_transformed df into a numpy array and then into a RecordSet. This is the required format for passing training data into a KMeans model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10306997",
   "metadata": {},
   "outputs": [],
   "source": [
    "# convert the transformed dataframe into record_set data\n",
    "kmeans_train_data_np = data_transformed.values.astype('float32')\n",
    "kmeans_formatted_data = kmeans.record_set(kmeans_train_data_np)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "44bad828",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "\n",
    "# train kmeans\n",
    "kmeans.fit(kmeans_formatted_data)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a8ccbb9f",
   "metadata": {},
   "source": [
    "#### Deploy the k-means model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a673676d",
   "metadata": {},
   "outputs": [],
   "source": [
    "%%time\n",
    "# deploy the model to create a predictor\n",
    "kmeans_predictor = kmeans.deploy(initial_instance_count=1, \n",
    "                                 instance_type='ml.p2.xlarge')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "edeb820a",
   "metadata": {},
   "source": [
    "#### Pass in the training data and assign predicted cluster labels\n",
    "After deploying the model, you can pass in the k-means training data, as a numpy array, and get resultant, predicted cluster labels for each data point."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20593140",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get the predicted clusters for all the kmeans training data\n",
    "cluster_info=kmeans_predictor.predict(kmeans_train_data_np)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "81020143",
   "metadata": {},
   "source": [
    "#### Exploring the resultant clusters\n",
    "The resulting predictions should give you information about the cluster that each data point belongs to."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21d30db9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# print cluster info for first data point\n",
    "data_idx = 0\n",
    "\n",
    "print('Person is: ', data_transformed.index[data_idx])\n",
    "print()\n",
    "print(cluster_info[data_idx])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "144719db",
   "metadata": {},
   "source": [
    "#### Visualize the distribution of data over clusters\n",
    "Get the cluster labels for each of our data points (counties) and visualize the distribution of points over each cluster."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3075a2d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get all cluster labels\n",
    "cluster_labels = [c.label['closest_cluster'].float32_tensor.values[0] for c in cluster_info]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8d9c33e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# count up the points in each cluster\n",
    "cluster_df = pd.DataFrame(cluster_labels)[0].value_counts()\n",
    "\n",
    "print(cluster_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "822d5249",
   "metadata": {},
   "outputs": [],
   "source": [
    "ax =plt.subplots(figsize=(6,3))\n",
    "ax = plt.hist(cluster_labels, bins=8,  range=(-0.5, 2.5), color='blue', rwidth=0.5)\n",
    "\n",
    "title=\"Histogram of Cluster Counts\"\n",
    "plt.title(title, fontsize=12)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "66c600dd",
   "metadata": {},
   "source": [
    "#### Delete the Endpoint!\n",
    "Now that you've deployed the k-means model and extracted the cluster labels for each data point, you no longer need the k-means endpoint."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3f62173",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Delete kmeans endpoint\n",
    "session.delete_endpoint(kmeans_predictor.endpoint)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97e5423d",
   "metadata": {},
   "source": [
    "### Model Attributes & Explainability\n",
    "Explaining the result of the modeling is an important step in making use of our analysis. By combining PCA and k-means, and the information contained in the model attributes within a SageMaker trained model, you can learn about a population and remark on some patterns you've found, based on the data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03919779",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download and unzip the kmeans model file\n",
    "kmeans_job_name = 'kmeans-2021-06-19-18-15-16-449'\n",
    "\n",
    "model_key = os.path.join(prefix, kmeans_job_name, 'output/model.tar.gz')\n",
    "\n",
    "# download the model file\n",
    "boto3.resource('s3').Bucket(bucket_name).download_file(model_key, 'model.tar.gz')\n",
    "os.system('tar -zxvf model.tar.gz')\n",
    "os.system('unzip model_algo-1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55ef0251",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Get the trained kmeans params using mxnet\n",
    "kmeans_model_params = mx.ndarray.load('model_algo-1')\n",
    "\n",
    "print(kmeans_model_params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e7b12e5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get all the centroids\n",
    "cluster_centroids = pd.DataFrame(kmeans_model_params[0].asnumpy())\n",
    "cluster_centroids.columns = data_transformed.columns\n",
    "\n",
    "display(cluster_centroids)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aad32aa0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save clusteres\n",
    "cluster_centroids.to_csv('saved_progress/cluster_centroids.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3bf33686",
   "metadata": {},
   "source": [
    "#### Visualizing Centroids in Component Space"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb661436",
   "metadata": {},
   "outputs": [],
   "source": [
    "# generate a heatmap in component space, using the seaborn library\n",
    "plt.figure(figsize = (12,9))\n",
    "ax = sns.heatmap(cluster_centroids.T, cmap = 'YlGnBu')\n",
    "ax.set_xlabel(\"Cluster\")\n",
    "plt.yticks(fontsize = 16)\n",
    "plt.xticks(fontsize = 16)\n",
    "ax.set_title(\"Attribute Value by Centroid\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8eb2dd3b",
   "metadata": {},
   "source": [
    "#### Natural Grouping"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83b9b541",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# add a 'labels' column to the dataframe\n",
    "data_transformed['labels']=list(map(int, cluster_labels))\n",
    "\n",
    "# sort by cluster label 0-6\n",
    "sorted_clients = data_transformed.sort_values('labels', ascending=True)\n",
    "# view some pts in cluster 0\n",
    "sorted_clients.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6bef8cb6",
   "metadata": {},
   "outputs": [],
   "source": [
    "cluster_centroids.to_csv('saved_progress/kmeans_clusters.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8f3d3328",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get all counties with label == 1\n",
    "cluster = data_transformed[data_transformed['labels']==1]\n",
    "cluster.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28c56d79",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install hdbscan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69d9ca40",
   "metadata": {},
   "outputs": [],
   "source": [
    "import hdbscan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5dde23db",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv('saved_progress/scaled_dataset.csv')\n",
    "data.drop(columns=[\"Unnamed: 0\" ], inplace=True)\n",
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb48752d",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = data.to_numpy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "057373de",
   "metadata": {},
   "outputs": [],
   "source": [
    "clusterer = hdbscan.HDBSCAN(min_cluster_size=25, gen_min_span_tree=True)\n",
    "clusterer.fit(data)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "593989f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "clusterer.minimum_spanning_tree_.plot(edge_cmap='viridis', \n",
    "                                      edge_alpha=0.6, \n",
    "                                      node_size=80, \n",
    "                                      edge_linewidth=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "323ce12b",
   "metadata": {},
   "outputs": [],
   "source": [
    "labels = pd.DataFrame(clusterer.labels_)\n",
    "labels[0].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "e586676c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: hdbscan==0.8.27 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (0.8.27)\n",
      "Requirement already satisfied: cython>=0.27 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (0.29.22)\n",
      "Requirement already satisfied: joblib>=1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (1.0.1)\n",
      "Requirement already satisfied: six in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (1.15.0)\n",
      "Requirement already satisfied: scipy>=1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (1.5.3)\n",
      "Requirement already satisfied: scikit-learn>=0.20 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (0.24.1)\n",
      "Requirement already satisfied: numpy>=1.16 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from hdbscan==0.8.27) (1.19.5)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scikit-learn>=0.20->hdbscan==0.8.27) (2.1.0)\n",
      "Requirement already satisfied: pip in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (21.1.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install hdbscan==0.8.27\n",
    "!pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "4e9fe7c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "train_instance_type has been renamed in sagemaker>=2.\n",
      "See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.\n",
      "train_instance_count has been renamed in sagemaker>=2.\n",
      "See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.\n",
      "train_instance_count has been renamed in sagemaker>=2.\n",
      "See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.\n",
      "train_instance_type has been renamed in sagemaker>=2.\n",
      "See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# your import and estimator code, here\n",
    "from sagemaker.sklearn.estimator import SKLearn\n",
    "\n",
    "estimator = SKLearn(entry_point=\"train.py\",\n",
    "                    source_dir=\"source_sklearn\",\n",
    "                    role=role,\n",
    "                    framework_version=\"0.20.0\",\n",
    "                    py_version=\"py3\",\n",
    "                    train_instance_count=1,\n",
    "                    train_instance_type='ml.c4.xlarge')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f7d2c181",
   "metadata": {},
   "outputs": [],
   "source": [
    "# !pip install -r \"source_sklearn/requirements.txt\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "a9710a6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2021-06-22 05:41:13 Starting - Starting the training job...\n",
      "2021-06-22 05:41:15 Starting - Launching requested ML instancesProfilerReport-1624340473: InProgress\n",
      "...\n",
      "2021-06-22 05:42:11 Starting - Preparing the instances for training.........\n",
      "2021-06-22 05:43:41 Downloading - Downloading input data...\n",
      "2021-06-22 05:44:09 Training - Downloading the training image..\u001b[34m2021-06-22 05:44:24,739 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training\u001b[0m\n",
      "\u001b[34m2021-06-22 05:44:24,741 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)\u001b[0m\n",
      "\u001b[34m2021-06-22 05:44:24,751 sagemaker_sklearn_container.training INFO     Invoking user training script.\u001b[0m\n",
      "\n",
      "2021-06-22 05:44:29 Training - Training image download completed. Training in progress.\u001b[34m2021-06-22 05:45:09,401 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)\u001b[0m\n",
      "\u001b[34m2021-06-22 05:45:09,413 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)\u001b[0m\n",
      "\u001b[34m2021-06-22 05:45:09,425 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)\u001b[0m\n",
      "\u001b[34m2021-06-22 05:45:09,435 sagemaker-training-toolkit INFO     Invoking user script\n",
      "\u001b[0m\n",
      "\u001b[34mTraining Env:\n",
      "\u001b[0m\n",
      "\u001b[34m{\n",
      "    \"additional_framework_parameters\": {},\n",
      "    \"channel_input_dirs\": {\n",
      "        \"train\": \"/opt/ml/input/data/train\"\n",
      "    },\n",
      "    \"current_host\": \"algo-1\",\n",
      "    \"framework_module\": \"sagemaker_sklearn_container.training:main\",\n",
      "    \"hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"hyperparameters\": {},\n",
      "    \"input_config_dir\": \"/opt/ml/input/config\",\n",
      "    \"input_data_config\": {\n",
      "        \"train\": {\n",
      "            \"TrainingInputMode\": \"File\",\n",
      "            \"S3DistributionType\": \"FullyReplicated\",\n",
      "            \"RecordWrapperType\": \"None\"\n",
      "        }\n",
      "    },\n",
      "    \"input_dir\": \"/opt/ml/input\",\n",
      "    \"is_master\": true,\n",
      "    \"job_name\": \"sagemaker-scikit-learn-2021-06-22-05-41-13-397\",\n",
      "    \"log_level\": 20,\n",
      "    \"master_hostname\": \"algo-1\",\n",
      "    \"model_dir\": \"/opt/ml/model\",\n",
      "    \"module_dir\": \"s3://sagemaker-us-east-1-305472246504/sagemaker-scikit-learn-2021-06-22-05-41-13-397/source/sourcedir.tar.gz\",\n",
      "    \"module_name\": \"train\",\n",
      "    \"network_interface_name\": \"eth0\",\n",
      "    \"num_cpus\": 4,\n",
      "    \"num_gpus\": 0,\n",
      "    \"output_data_dir\": \"/opt/ml/output/data\",\n",
      "    \"output_dir\": \"/opt/ml/output\",\n",
      "    \"output_intermediate_dir\": \"/opt/ml/output/intermediate\",\n",
      "    \"resource_config\": {\n",
      "        \"current_host\": \"algo-1\",\n",
      "        \"hosts\": [\n",
      "            \"algo-1\"\n",
      "        ],\n",
      "        \"network_interface_name\": \"eth0\"\n",
      "    },\n",
      "    \"user_entry_point\": \"train.py\"\u001b[0m\n",
      "\u001b[34m}\n",
      "\u001b[0m\n",
      "\u001b[34mEnvironment variables:\n",
      "\u001b[0m\n",
      "\u001b[34mSM_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_NETWORK_INTERFACE_NAME=eth0\u001b[0m\n",
      "\u001b[34mSM_HPS={}\u001b[0m\n",
      "\u001b[34mSM_USER_ENTRY_POINT=train.py\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_PARAMS={}\u001b[0m\n",
      "\u001b[34mSM_RESOURCE_CONFIG={\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"}\u001b[0m\n",
      "\u001b[34mSM_INPUT_DATA_CONFIG={\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}}\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DATA_DIR=/opt/ml/output/data\u001b[0m\n",
      "\u001b[34mSM_CHANNELS=[\"train\"]\u001b[0m\n",
      "\u001b[34mSM_CURRENT_HOST=algo-1\u001b[0m\n",
      "\u001b[34mSM_MODULE_NAME=train\u001b[0m\n",
      "\u001b[34mSM_LOG_LEVEL=20\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_MODULE=sagemaker_sklearn_container.training:main\u001b[0m\n",
      "\u001b[34mSM_INPUT_DIR=/opt/ml/input\u001b[0m\n",
      "\u001b[34mSM_INPUT_CONFIG_DIR=/opt/ml/input/config\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DIR=/opt/ml/output\u001b[0m\n",
      "\u001b[34mSM_NUM_CPUS=4\u001b[0m\n",
      "\u001b[34mSM_NUM_GPUS=0\u001b[0m\n",
      "\u001b[34mSM_MODEL_DIR=/opt/ml/model\u001b[0m\n",
      "\u001b[34mSM_MODULE_DIR=s3://sagemaker-us-east-1-305472246504/sagemaker-scikit-learn-2021-06-22-05-41-13-397/source/sourcedir.tar.gz\u001b[0m\n",
      "\u001b[34mSM_TRAINING_ENV={\"additional_framework_parameters\":{},\"channel_input_dirs\":{\"train\":\"/opt/ml/input/data/train\"},\"current_host\":\"algo-1\",\"framework_module\":\"sagemaker_sklearn_container.training:main\",\"hosts\":[\"algo-1\"],\"hyperparameters\":{},\"input_config_dir\":\"/opt/ml/input/config\",\"input_data_config\":{\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}},\"input_dir\":\"/opt/ml/input\",\"is_master\":true,\"job_name\":\"sagemaker-scikit-learn-2021-06-22-05-41-13-397\",\"log_level\":20,\"master_hostname\":\"algo-1\",\"model_dir\":\"/opt/ml/model\",\"module_dir\":\"s3://sagemaker-us-east-1-305472246504/sagemaker-scikit-learn-2021-06-22-05-41-13-397/source/sourcedir.tar.gz\",\"module_name\":\"train\",\"network_interface_name\":\"eth0\",\"num_cpus\":4,\"num_gpus\":0,\"output_data_dir\":\"/opt/ml/output/data\",\"output_dir\":\"/opt/ml/output\",\"output_intermediate_dir\":\"/opt/ml/output/intermediate\",\"resource_config\":{\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"},\"user_entry_point\":\"train.py\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ARGS=[]\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate\u001b[0m\n",
      "\u001b[34mSM_CHANNEL_TRAIN=/opt/ml/input/data/train\u001b[0m\n",
      "\u001b[34mPYTHONPATH=/opt/ml/code:/miniconda3/bin:/miniconda3/lib/python37.zip:/miniconda3/lib/python3.7:/miniconda3/lib/python3.7/lib-dynload:/miniconda3/lib/python3.7/site-packages\n",
      "\u001b[0m\n",
      "\u001b[34mInvoking script with the following command:\n",
      "\u001b[0m\n",
      "\u001b[34m/miniconda3/bin/python train.py\n",
      "\n",
      "\u001b[0m\n",
      "\u001b[34m/miniconda3/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n",
      "  import imp\u001b[0m\n",
      "\u001b[34mWARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.\u001b[0m\n",
      "\u001b[34mPlease see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.\u001b[0m\n",
      "\u001b[34mTo avoid this problem you can invoke Python with '-m pip' instead of running pip directly.\u001b[0m\n",
      "\u001b[34mCollecting hdbscan\n",
      "  Downloading hdbscan-0.8.27.tar.gz (6.4 MB)\u001b[0m\n",
      "\u001b[34m  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-f__timde/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/32/bb/59a75bc5ac66a9b4f9b8f979e4545af0e98bb1ca4e6ae96b3b956b554223/hdbscan-0.8.27.tar.gz#sha256=e3a418d0d36874f7b6a1bf0b7461f3857fc13a525fd48ba34caed2fe8973aa26 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-f__timde/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.26.tar.gz (4.7 MB)\n",
      "  Installing build dependencies: started\u001b[0m\n",
      "\u001b[34m  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-35l7n98n/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/22/2f/2423d844072f007a74214c1adc46260e45f034bb1679ccadfbb8a601f647/hdbscan-0.8.26.tar.gz#sha256=81a61cd011e010b20e7cbd8d235053a98892504d32881d379d1902278817927e (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-35l7n98n/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.25.tar.gz (4.4 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-thtw9v_4/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/8a/a6/2524f6cff01a2da18f07f6a2b04977297f8a094ef3a92aa6bfc6c3924687/hdbscan-0.8.25.tar.gz#sha256=92cccf0cfcb544007529841a387e97379cfe5d2d33ab620777cf2b17a925b19e (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-thtw9v_4/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.24.tar.gz (4.4 MB)\n",
      "  Installing build dependencies: started\u001b[0m\n",
      "\u001b[34m  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-m8wj7ozq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/9f/db/c3e6b58518d0a19861eb0309670b8432a2237acae253db92ba9b523f9082/hdbscan-0.8.24.tar.gz#sha256=fe31a7ea0ce2c9babd190a195e491834ff9f64c74daa4ca94fa65a88f701269a (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-m8wj7ozq/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.23.tar.gz (4.9 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vdb7999h/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/18/35/a117860dd7f38eb1a77e4e30ac69a63c45c5a6356f503874fbe80fc464b7/hdbscan-0.8.23.tar.gz#sha256=ff60c66591452ceb6bdb7592c560a1ebc7e128a02dd3880e048861f7fea7f78d (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vdb7999h/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.22.tar.gz (4.0 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ssb91upo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/10/7c/1401ec61b0e7392287e045b6913206cfff050b65d869c19f7ec0f5626487/hdbscan-0.8.22.tar.gz#sha256=5cfdc25375123eb9a72363449979141cc928c1953f220f0f81d7baabcaccec2d (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ssb91upo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\u001b[0m\n",
      "\u001b[34m  Downloading hdbscan-0.8.21.tar.gz (4.0 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-58pdnh2l/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/b2/cd/6ae33e3cc932c05273778dc1d8d61f3934c66fc330518241f06eb3d4c489/hdbscan-0.8.21.tar.gz#sha256=1bf3132763d4d3dc5678f037003b6df657a242437743060787566d6fcaec52b5 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-58pdnh2l/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.20.tar.gz (4.0 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-fr2tsuvc/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/c8/c5/99f2a386b2dd716b82d377a1a605d03d8734a14686f8d192c76785f481fd/hdbscan-0.8.20.tar.gz#sha256=263e9f34db63eec217d50f2ca3e65049c065775dc4095b5ee817824cd2b5b51b (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-fr2tsuvc/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.19.tar.gz (4.0 MB)\u001b[0m\n",
      "\u001b[34m  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ubpwguq5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/22/8d/1fc4bfd17ae871441fd6440abc3da5fdecf34831aa711e3e52727ab00556/hdbscan-0.8.19.tar.gz#sha256=7bd74c7bd16540d7f437cf6cb61ceb4d23506f4d040c436d7570d104c1297e31 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ubpwguq5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.18.tar.gz (4.0 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-t7q7a8vm/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/aa/30/97f3fc4f1f1fdb8f2c77aef720758ea3e8251c43bb092cb0d64bde76fb78/hdbscan-0.8.18.tar.gz#sha256=4d6782f08872f4c54983873a41759daae680d6247b0db363f3510cb001108f02 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-t7q7a8vm/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.17.tar.gz (4.0 MB)\u001b[0m\n",
      "\u001b[34m  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qyg3h1jb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy\n",
      "       cwd: None\n",
      "  Complete output (42 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "      \"__main__\", mod_spec)\n",
      "    File \"/miniconda3/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "      exec(code, run_globals)\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/__main__.py\", line 24, in <module>\n",
      "      sys.exit(_main())\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py\", line 71, in main\n",
      "      command = create_command(cmd_name, isolated=(\"--isolated\" in cmd_args))\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/__init__.py\", line 96, in create_command\n",
      "      module = importlib.import_module(module_path)\n",
      "    File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py\", line 15, in <module>\n",
      "      from pip._internal.cli.req_command import RequirementCommand, with_cleanup\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py\", line 16, in <module>\n",
      "      from pip._internal.index.collector import LinkCollector\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_internal/index/collector.py\", line 16, in <module>\n",
      "      from pip._vendor import html5lib, requests\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py\", line 123, in <module>\n",
      "      from . import utils\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/utils.py\", line 25, in <module>\n",
      "      from . import certs\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/requests/certs.py\", line 15, in <module>\n",
      "      from pip._vendor.certifi import where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py\", line 1, in <module>\n",
      "      from .core import contents, where\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/pip/_vendor/certifi/core.py\", line 12, in <module>\n",
      "      from importlib.resources import path as get_path, read_text\n",
      "    File \"/miniconda3/lib/python3.7/importlib/resources.py\", line 11, in <module>\n",
      "      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1359, in <module>\n",
      "      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):\n",
      "    File \"/miniconda3/lib/python3.7/site-packages/typing.py\", line 1007, in __new__\n",
      "      self._abc_registry = extra._abc_registry\n",
      "  AttributeError: type object 'Callable' has no attribute '_abc_registry'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/c6/98/911ad64e293e8be804d471956c5692280072a97384a13a365989bbf8b7af/hdbscan-0.8.17.tar.gz#sha256=7ed08fc0573dd50b008a4d3f833a824888b81aec5c558eec131d36c822a5c41a (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: /miniconda3/bin/python /miniconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qyg3h1jb/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.16.tar.gz (4.0 MB)\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: /miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kjbjuq3q\n",
      "         cwd: /tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/\n",
      "    Complete output (9 lines):\n",
      "    /tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/setup.py:8: UserWarning: No module named 'Cython'\n",
      "      warnings.warn(e.args[0])\n",
      "    /tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/setup.py:91: UserWarning: Due to incompatibilities with Python 3.7 hdbscan nowrequires Cython to be installed in order to build it\n",
      "      warnings.warn('Due to incompatibilities with Python 3.7 hdbscan now'\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-zq921fan/hdbscan_978f8477c85d462d97f712145916e574/setup.py\", line 93, in <module>\n",
      "        raise ImportError('Cython not found! Please install cython and try again')\n",
      "    ImportError: Cython not found! Please install cython and try again\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/bb/49/df8f8092844d06bd4e1e98e13f960f479f6e3c7d21ca583511a3cbfbeab2/hdbscan-0.8.16.tar.gz#sha256=025cb58039d5a6ca73fee93243c5c034f9366c08c035f7c73b810068dfe31599 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.15.tar.gz (4.0 MB)\u001b[0m\n",
      "\u001b[34m    ERROR: Command errored out with exit status 1:\n",
      "     command: /miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2anepk7d\n",
      "         cwd: /tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/\n",
      "    Complete output (9 lines):\n",
      "    /tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/setup.py:8: UserWarning: No module named 'Cython'\n",
      "      warnings.warn(e.args[0])\n",
      "    /tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/setup.py:91: UserWarning: Due to incompatibilities with Python 3.7 hdbscan nowrequires Cython to be installed in order to build it\n",
      "      warnings.warn('Due to incompatibilities with Python 3.7 hdbscan now'\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-zq921fan/hdbscan_7b3938d959e24086bcd3d09bc7cf9c87/setup.py\", line 93, in <module>\n",
      "        raise ImportError('Cython not found! Please install cython and try again')\n",
      "    ImportError: Cython not found! Please install cython and try again\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/ce/7a/7d24b0aacdc05f0c0c04d6bbda05dc006ff15fc64bb63282fbfc05da9965/hdbscan-0.8.15.tar.gz#sha256=446f98e1ea622a39c1f396d839fa2b1c35db98234e373336de61c3bd6ffaec78 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.14.tar.gz (4.0 MB)\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: /miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6iv9w8cv\n",
      "         cwd: /tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/\n",
      "    Complete output (9 lines):\n",
      "    /tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/setup.py:8: UserWarning: No module named 'Cython'\n",
      "      warnings.warn(e.args[0])\n",
      "    /tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/setup.py:91: UserWarning: Due to incompatibilities with Python 3.7 hdbscan nowrequires Cython to be installed in order to build it\n",
      "      warnings.warn('Due to incompatibilities with Python 3.7 hdbscan now'\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/tmp/pip-install-zq921fan/hdbscan_7cb7a703e2cb4bd0934910fdc4d76198/setup.py\", line 93, in <module>\n",
      "        raise ImportError('Cython not found! Please install cython and try again')\n",
      "    ImportError: Cython not found! Please install cython and try again\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[34mWARNING: Discarding https://files.pythonhosted.org/packages/19/11/9471a7fcc23b8a9d409646217b2cdb5ba260d0d691fd2fd691976a290225/hdbscan-0.8.14.tar.gz#sha256=0dcf42e1112bcf266e7a1d7ffbc16e6a4a0f4c58a0a371c7224de25413d83b56 (from https://pypi.org/simple/hdbscan/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  Downloading hdbscan-0.8.13.tar.gz (5.1 MB)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: numpy in /miniconda3/lib/python3.7/site-packages (from hdbscan) (1.20.1)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: scikit-learn>=0.16 in /miniconda3/lib/python3.7/site-packages (from hdbscan) (0.20.0)\u001b[0m\n",
      "\u001b[34mRequirement already satisfied: scipy>=0.13.3 in /miniconda3/lib/python3.7/site-packages (from scikit-learn>=0.16->hdbscan) (1.6.2)\u001b[0m\n",
      "\u001b[34mBuilding wheels for collected packages: hdbscan\n",
      "  Building wheel for hdbscan (setup.py): started\u001b[0m\n",
      "\u001b[34m  Building wheel for hdbscan (setup.py): finished with status 'error'\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: /miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /tmp/pip-wheel-5hyqlkik\n",
      "       cwd: /tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/\n",
      "  Complete output (107 lines):\n",
      "  /tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py:8: UserWarning: No module named 'Cython'\n",
      "    warnings.warn(e.args[0])\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build/lib.linux-x86_64-3.7\n",
      "  creating build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/robust_single_linkage_.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/prediction.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/plots.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/hdbscan_.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/__init__.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  copying hdbscan/validity.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "  creating build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "  copying hdbscan/tests/test_hdbscan.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "  copying hdbscan/tests/test_rsl.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "  copying hdbscan/tests/__init__.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "  warning: build_py: byte-compiling is disabled, skipping.\n",
      "  \n",
      "  running build_ext\n",
      "  building 'hdbscan._hdbscan_tree' extension\n",
      "  creating build/temp.linux-x86_64-3.7\n",
      "  creating build/temp.linux-x86_64-3.7/hdbscan\n",
      "  gcc -pthread -B /miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/miniconda3/include/python3.7m -I/miniconda3/lib/python3.7/site-packages/numpy/core/include -c hdbscan/_hdbscan_tree.c -o build/temp.linux-x86_64-3.7/hdbscan/_hdbscan_tree.o\n",
      "  In file included from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944:0,\n",
      "                   from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,\n",
      "                   from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,\n",
      "                   from hdbscan/_hdbscan_tree.c:274:\n",
      "  /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning \"Using deprecated NumPy API, disable it with \" \"#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]\n",
      "   #warning \"Using deprecated NumPy API, disable it with \" \\\n",
      "    ^\n",
      "  hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionSave’:\n",
      "  hdbscan/_hdbscan_tree.c:29556:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       *type = tstate->exc_type;\n",
      "                     ^\n",
      "  hdbscan/_hdbscan_tree.c:29557:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       *value = tstate->exc_value;\n",
      "                      ^\n",
      "  hdbscan/_hdbscan_tree.c:29558:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       *tb = tstate->exc_traceback;\n",
      "                   ^\n",
      "  hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionReset’:\n",
      "  hdbscan/_hdbscan_tree.c:29565:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tmp_type = tstate->exc_type;\n",
      "                        ^\n",
      "  hdbscan/_hdbscan_tree.c:29566:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tmp_value = tstate->exc_value;\n",
      "                         ^\n",
      "  hdbscan/_hdbscan_tree.c:29567:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tmp_tb = tstate->exc_traceback;\n",
      "                      ^\n",
      "  hdbscan/_hdbscan_tree.c:29568:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tstate->exc_type = type;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29569:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tstate->exc_value = value;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29570:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tstate->exc_traceback = tb;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c: In function ‘__Pyx__GetException’:\n",
      "  hdbscan/_hdbscan_tree.c:29625:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tmp_type = tstate->exc_type;\n",
      "                        ^\n",
      "  hdbscan/_hdbscan_tree.c:29626:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tmp_value = tstate->exc_value;\n",
      "                         ^\n",
      "  hdbscan/_hdbscan_tree.c:29627:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tmp_tb = tstate->exc_traceback;\n",
      "                      ^\n",
      "  hdbscan/_hdbscan_tree.c:29628:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tstate->exc_type = local_type;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29629:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tstate->exc_value = local_value;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29630:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tstate->exc_traceback = local_tb;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionSwap’:\n",
      "  hdbscan/_hdbscan_tree.c:29652:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tmp_type = tstate->exc_type;\n",
      "                        ^\n",
      "  hdbscan/_hdbscan_tree.c:29653:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tmp_value = tstate->exc_value;\n",
      "                         ^\n",
      "  hdbscan/_hdbscan_tree.c:29654:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tmp_tb = tstate->exc_traceback;\n",
      "                      ^\n",
      "  hdbscan/_hdbscan_tree.c:29655:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "       tstate->exc_type = *type;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29656:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "       tstate->exc_value = *value;\n",
      "             ^\n",
      "  hdbscan/_hdbscan_tree.c:29657:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "       tstate->exc_traceback = *tb;\n",
      "             ^\n",
      "  In file included from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:21:0,\n",
      "                   from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,\n",
      "                   from hdbscan/_hdbscan_tree.c:274:\n",
      "  hdbscan/_hdbscan_tree.c: At top level:\n",
      "  /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1464:1: warning: ‘_import_array’ defined but not used [-Wunused-function]\n",
      "   _import_array(void)\n",
      "   ^\n",
      "  error: command 'gcc' failed with exit status 1\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for hdbscan\n",
      "  Running setup.py clean for hdbscan\u001b[0m\n",
      "\u001b[34mFailed to build hdbscan\u001b[0m\n",
      "\u001b[34mInstalling collected packages: hdbscan\n",
      "    Running setup.py install for hdbscan: started\u001b[0m\n",
      "\u001b[34m    Running setup.py install for hdbscan: finished with status 'error'\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: /miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-yh9s6shy/install-record.txt --single-version-externally-managed --compile --install-headers /miniconda3/include/python3.7m/hdbscan\n",
      "         cwd: /tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/\n",
      "    Complete output (107 lines):\n",
      "    /tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py:8: UserWarning: No module named 'Cython'\n",
      "      warnings.warn(e.args[0])\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build/lib.linux-x86_64-3.7\n",
      "    creating build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/robust_single_linkage_.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/prediction.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/plots.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/hdbscan_.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/__init__.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    copying hdbscan/validity.py -> build/lib.linux-x86_64-3.7/hdbscan\n",
      "    creating build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "    copying hdbscan/tests/test_hdbscan.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "    copying hdbscan/tests/test_rsl.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "    copying hdbscan/tests/__init__.py -> build/lib.linux-x86_64-3.7/hdbscan/tests\n",
      "    warning: build_py: byte-compiling is disabled, skipping.\n",
      "    \n",
      "    running build_ext\n",
      "    building 'hdbscan._hdbscan_tree' extension\n",
      "    creating build/temp.linux-x86_64-3.7\n",
      "    creating build/temp.linux-x86_64-3.7/hdbscan\n",
      "    gcc -pthread -B /miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/miniconda3/include/python3.7m -I/miniconda3/lib/python3.7/site-packages/numpy/core/include -c hdbscan/_hdbscan_tree.c -o build/temp.linux-x86_64-3.7/hdbscan/_hdbscan_tree.o\n",
      "    In file included from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944:0,\n",
      "                     from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,\n",
      "                     from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,\n",
      "                     from hdbscan/_hdbscan_tree.c:274:\n",
      "    /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning \"Using deprecated NumPy API, disable it with \" \"#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]\n",
      "     #warning \"Using deprecated NumPy API, disable it with \" \\\n",
      "      ^\n",
      "    hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionSave’:\n",
      "    hdbscan/_hdbscan_tree.c:29556:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         *type = tstate->exc_type;\n",
      "                       ^\n",
      "    hdbscan/_hdbscan_tree.c:29557:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         *value = tstate->exc_value;\n",
      "                        ^\n",
      "    hdbscan/_hdbscan_tree.c:29558:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         *tb = tstate->exc_traceback;\n",
      "                     ^\n",
      "    hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionReset’:\n",
      "    hdbscan/_hdbscan_tree.c:29565:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tmp_type = tstate->exc_type;\n",
      "                          ^\n",
      "    hdbscan/_hdbscan_tree.c:29566:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tmp_value = tstate->exc_value;\n",
      "                           ^\n",
      "    hdbscan/_hdbscan_tree.c:29567:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tmp_tb = tstate->exc_traceback;\n",
      "                        ^\n",
      "    hdbscan/_hdbscan_tree.c:29568:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tstate->exc_type = type;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29569:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tstate->exc_value = value;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29570:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tstate->exc_traceback = tb;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c: In function ‘__Pyx__GetException’:\n",
      "    hdbscan/_hdbscan_tree.c:29625:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tmp_type = tstate->exc_type;\n",
      "                          ^\n",
      "    hdbscan/_hdbscan_tree.c:29626:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tmp_value = tstate->exc_value;\n",
      "                           ^\n",
      "    hdbscan/_hdbscan_tree.c:29627:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tmp_tb = tstate->exc_traceback;\n",
      "                        ^\n",
      "    hdbscan/_hdbscan_tree.c:29628:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tstate->exc_type = local_type;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29629:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tstate->exc_value = local_value;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29630:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tstate->exc_traceback = local_tb;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c: In function ‘__Pyx__ExceptionSwap’:\n",
      "    hdbscan/_hdbscan_tree.c:29652:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tmp_type = tstate->exc_type;\n",
      "                          ^\n",
      "    hdbscan/_hdbscan_tree.c:29653:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tmp_value = tstate->exc_value;\n",
      "                           ^\n",
      "    hdbscan/_hdbscan_tree.c:29654:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tmp_tb = tstate->exc_traceback;\n",
      "                        ^\n",
      "    hdbscan/_hdbscan_tree.c:29655:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’\n",
      "         tstate->exc_type = *type;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29656:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’\n",
      "         tstate->exc_value = *value;\n",
      "               ^\n",
      "    hdbscan/_hdbscan_tree.c:29657:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’\n",
      "         tstate->exc_traceback = *tb;\n",
      "               ^\n",
      "    In file included from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:21:0,\n",
      "                     from /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,\n",
      "                     from hdbscan/_hdbscan_tree.c:274:\n",
      "    hdbscan/_hdbscan_tree.c: At top level:\n",
      "    /miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1464:1: warning: ‘_import_array’ defined but not used [-Wunused-function]\n",
      "     _import_array(void)\n",
      "     ^\n",
      "    error: command 'gcc' failed with exit status 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[34mERROR: Command errored out with exit status 1: /miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-zq921fan/hdbscan_4f961611d8a64c2c8c150d9b8903610c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-yh9s6shy/install-record.txt --single-version-externally-managed --compile --install-headers /miniconda3/include/python3.7m/hdbscan Check the logs for full command output.\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"train.py\", line 62, in <module>\n",
      "    install_and_import('hdbscan')\n",
      "  File \"train.py\", line 19, in install_and_import\n",
      "    globals()[package] = importlib.import_module(package)\n",
      "  File \"/miniconda3/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\u001b[0m\n",
      "\u001b[34mModuleNotFoundError: No module named 'hdbscan'\u001b[0m\n",
      "\u001b[34m2021-06-22 05:45:20,826 sagemaker-containers ERROR    Reporting training FAILURE\u001b[0m\n",
      "\u001b[34m2021-06-22 05:45:20,827 sagemaker-containers ERROR    framework error: \u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py\", line 84, in train\n",
      "    entrypoint()\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 39, in main\n",
      "    train(environment.Environment())\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 35, in train\n",
      "    runner_type=runner.ProcessRunnerType)\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py\", line 100, in run\n",
      "    wait, capture_error\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 164, in run\n",
      "    cwd=environment.code_dir,\n",
      "  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 84, in check_error\n",
      "    raise error_class(return_code=return_code, cmd=\" \".join(cmd), output=stderr)\u001b[0m\n",
      "\u001b[34msagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mCommand \"/miniconda3/bin/python train.py\"\n",
      "\u001b[0m\n",
      "\u001b[34mExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mCommand \"/miniconda3/bin/python train.py\"\u001b[0m\n",
      "\n",
      "2021-06-22 05:45:32 Uploading - Uploading generated training model\n",
      "2021-06-22 05:45:32 Failed - Training job failed\n",
      "ProfilerReport-1624340473: Stopping\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Training job sagemaker-scikit-learn-2021-06-22-05-41-13-397: Failed. Reason: AlgorithmError: framework error: \nTraceback (most recent call last):\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py\", line 84, in train\n    entrypoint()\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 39, in main\n    train(environment.Environment())\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 35, in train\n    runner_type=runner.ProcessRunnerType)\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py\", line 100, in run\n    wait, capture_error\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 164, in run\n    cwd=environment.code_dir,\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 84, in check_error\n    raise error_class(return_code=return_code, cmd=\" \".join(cmd), output=stderr)\nsagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:\nCommand \"/miniconda3/bin/python ",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<timed eval>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m    680\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    681\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 682\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    683\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    684\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_compilation_job_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   1623\u001b[0m         \u001b[0;31m# If logs are requested, call logs_for_jobs.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1624\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1625\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1626\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1627\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   3679\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3680\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3681\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3682\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3683\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   3243\u001b[0m                 ),\n\u001b[1;32m   3244\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3245\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3246\u001b[0m             )\n\u001b[1;32m   3247\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job sagemaker-scikit-learn-2021-06-22-05-41-13-397: Failed. Reason: AlgorithmError: framework error: \nTraceback (most recent call last):\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py\", line 84, in train\n    entrypoint()\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 39, in main\n    train(environment.Environment())\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py\", line 35, in train\n    runner_type=runner.ProcessRunnerType)\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py\", line 100, in run\n    wait, capture_error\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 164, in run\n    cwd=environment.code_dir,\n  File \"/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py\", line 84, in check_error\n    raise error_class(return_code=return_code, cmd=\" \".join(cmd), output=stderr)\nsagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:\nCommand \"/miniconda3/bin/python "
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "# Train your estimator on S3 training data\n",
    "estimator.fit({'train': input_data})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d7500519",
   "metadata": {},
   "outputs": [
    {
     "ename": "ClientError",
     "evalue": "An error occurred (ValidationException) when calling the CreateModel operation: Could not find model data at s3://sagemaker-us-east-1-305472246504/sagemaker-scikit-learn-2021-06-22-04-48-20-397/output/model.tar.gz.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mClientError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<timed exec>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mdeploy\u001b[0;34m(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)\u001b[0m\n\u001b[1;32m    949\u001b[0m             \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    950\u001b[0m             \u001b[0mkms_key\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mkms_key\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 951\u001b[0;31m             \u001b[0mdata_capture_config\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdata_capture_config\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    952\u001b[0m         )\n\u001b[1;32m    953\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/model.py\u001b[0m in \u001b[0;36mdeploy\u001b[0;34m(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, **kwargs)\u001b[0m\n\u001b[1;32m    761\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_base_name\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"-\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_base_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompiled_model_suffix\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    762\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 763\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_create_sagemaker_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minstance_type\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maccelerator_type\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtags\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    764\u001b[0m         production_variant = sagemaker.production_variant(\n\u001b[1;32m    765\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minstance_type\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minitial_instance_count\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maccelerator_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0maccelerator_type\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/model.py\u001b[0m in \u001b[0;36m_create_sagemaker_model\u001b[0;34m(self, instance_type, accelerator_type, tags)\u001b[0m\n\u001b[1;32m    329\u001b[0m             \u001b[0mvpc_config\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvpc_config\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    330\u001b[0m             \u001b[0menable_network_isolation\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0menable_network_isolation\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 331\u001b[0;31m             \u001b[0mtags\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtags\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    332\u001b[0m         )\n\u001b[1;32m    333\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mcreate_model\u001b[0;34m(self, name, role, container_defs, vpc_config, enable_network_isolation, primary_container, tags)\u001b[0m\n\u001b[1;32m   2554\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2555\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2556\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_client\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcreate_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mcreate_model_request\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2557\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mClientError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2558\u001b[0m             \u001b[0merror_code\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Error\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Code\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/botocore/client.py\u001b[0m in \u001b[0;36m_api_call\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    384\u001b[0m                     \"%s() only accepts keyword arguments.\" % py_operation_name)\n\u001b[1;32m    385\u001b[0m             \u001b[0;31m# The \"self\" in this scope is referring to the BaseClient.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 386\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_api_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moperation_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    387\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    388\u001b[0m         \u001b[0m_api_call\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpy_operation_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/botocore/client.py\u001b[0m in \u001b[0;36m_make_api_call\u001b[0;34m(self, operation_name, api_params)\u001b[0m\n\u001b[1;32m    703\u001b[0m             \u001b[0merror_code\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Error\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Code\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    704\u001b[0m             \u001b[0merror_class\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexceptions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_code\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror_code\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 705\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0merror_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparsed_response\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moperation_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    706\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    707\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mparsed_response\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mClientError\u001b[0m: An error occurred (ValidationException) when calling the CreateModel operation: Could not find model data at s3://sagemaker-us-east-1-305472246504/sagemaker-scikit-learn-2021-06-22-04-48-20-397/output/model.tar.gz."
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "# uncomment, if needed\n",
    "# from sagemaker.pytorch import PyTorchModel\n",
    "\n",
    "\n",
    "# deploy your model to create a predictor\n",
    "predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.t2.medium')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6fdf21a4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
